eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true

server:
  port: 8806

spring:
  application:
    name: back-http

  servlet:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      file-size-threshold: 100MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: D:/

# 开启熔断
feign:
  hystrix:
    enabled: true

upload-folder: d:/a/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200000 #缺省为1000