eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true
server:
  port: 8771
  servlet:
    context-path: /

spring:
  application:
    name: ZUUL-SERVICE

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

  routes:
    USER-HTTP:
      path: /user-http/**
    TEST-CLIENT:
      path: /test-client/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  # 请求处理超时时间
  ReadTimeout: 160000
  # 请求连接超时时间
  ConnectTimeout: 60000
