eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true
server:
  port: 8771
  servlet:
    context-path: /

spring:
  application:
    name: ZUUL-SERVICE
  servlet:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      file-size-threshold: 100MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: D:/

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

  routes:
    USER-HTTP:
      path: /user-http/**
    VIDEO-HTTP:
      path: /video-http/**
    TEST-CLIENT:
      path: /test-client/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  # 请求处理超时时间
  ReadTimeout: 160000
  # 请求连接超时时间
  ConnectTimeout: 60000


