eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true
server:
  port: 8771
  servlet:
    context-path: /

spring:
  application:
    name: ZUUL-SERVICE

zuul:
  routes:
    USER-HTTP:
      path: /user-http/**